import React, { useState, useEffect, useRef, useCallback } from "react";
import {
  ChevronRight, ChevronDown, Check, Terminal, FileText, CornerDownLeft,
  Loader2, AlertCircle, ArrowRight, RotateCcw, Pencil, MessageSquare, Plus, Play,
  FolderGit2, ChevronsUpDown,
} from "lucide-react";
import V5WorkView from "./v5-work-view.jsx";

const api = {
  list: () => fetch("/api/reqs").then((r) => r.json()),
  get: (id) => fetch(`/api/req?id=${id}`).then((r) => r.json()),
  create: (title, projectId) => post("/api/reqs", { title, projectId }),
  message: (id, text, onEvent) => streamPost(`/api/message?id=${id}`, { text }, onEvent),
  implMessage: (id, text) => post(`/api/impl-message?id=${id}`, { text }),
  handoff: (id, onEvent) => streamPost(`/api/handoff?id=${id}`, {}, onEvent),
  run: (id, ticket, onEvent) => streamPost(`/api/run?id=${id}`, { ticket }, onEvent),
  settled: (id, settled) => post(`/api/settled?id=${id}`, { settled }),
  invalidate: (id, backToAnalysis) => post(`/api/invalidate?id=${id}`, { backToAnalysis }),
  start: (id) => post(`/api/start?id=${id}`, {}), stop: (id) => post(`/api/stop?id=${id}`, {}),
  stepReset: (id, ticket, skillName) => post(`/api/step-reset?id=${id}`, { ticket, skillName }),
  ticketReset: (id, ticket) => post(`/api/ticket-reset?id=${id}`, { ticket }), failureReason: (id, reason) => post(`/api/reqs/${id}/failure-reason`, { reason }),
  projects: { list: () => fetch("/api/projects").then((r) => r.json()), create: (p) => post("/api/projects", p) },
  works: { list: (projectId) => fetch(`/api/v5/works${projectId ? `?projectId=${projectId}` : ""}`).then((r) => r.json()), create: (title, projectId) => post("/api/v5/works", { title, projectId }) },
};
async function streamPost(url, body, onEvent) { const res = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const reader = res.body.getReader(); const dec = new TextDecoder(); let buf = "", final = null; for (;;) { const { done, value } = await reader.read(); if (done) break; buf += dec.decode(value, { stream: true }); const lines = buf.split("\n"); buf = lines.pop() ?? ""; for (const line of lines) { if (!line.trim()) continue; let e; try { e = JSON.parse(line); } catch { continue; } if (e.type === "done") final = e.req; else if (e.type === "error") throw new Error(e.message); else onEvent?.(e); } } return final; }
const post = (u, b) => fetch(u, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(b) }).then((r) => r.json());
function stripProtocol(t) { return String(t || "").replace(/^(SETTLED|VERDICT):[\s\S]*$/m, "").trimEnd(); }
function subscribeRun(id, onEvent, onEnd) { const ctrl = new AbortController(); (async () => { try { const res = await fetch(`/api/events?id=${id}`, { signal: ctrl.signal }); const reader = res.body.getReader(); const dec = new TextDecoder(); let buf = ""; for (;;) { const { done, value } = await reader.read(); if (done) break; buf += dec.decode(value, { stream: true }); const lines = buf.split("\n"); buf = lines.pop() ?? ""; for (const line of lines) { if (!line.trim()) continue; try { const e = JSON.parse(line); if (e.type !== "ping") onEvent(e); } catch {} } } } catch {} onEnd?.(); })(); return () => ctrl.abort(); }
const idFromUrl = () => new URLSearchParams(window.location.search).get("id");
const workIdFromUrl = () => new URLSearchParams(window.location.search).get("work");
function writeSelectionToUrl(id, workId) { const u = new URL(window.location.href); if (id) u.searchParams.set("id", id); else u.searchParams.delete("id"); if (workId) u.searchParams.set("work", workId); else u.searchParams.delete("work"); if (u.href !== window.location.href) window.history.replaceState(null, "", u); }
function fmtMs(ms) { if (!ms || ms < 0) return null; const s = Math.round(ms / 1000); if (s < 60) return `${s}s`; const m = Math.floor(s / 60); return `${m}m${String(s % 60).padStart(2, "0")}s`; }
function useElapsed(active) { const [ms, setMs] = useState(0); useEffect(() => { if (!active) return undefined; const t0 = Date.now(); setMs(0); const id = setInterval(() => setMs(Date.now() - t0), 1000); return () => clearInterval(id); }, [active]); return ms; }
function isOnePass(r) { if (r.phase !== "done" || r.everReset) return false; const skills = (r.tickets || []).flatMap((t) => t.skills); return skills.length > 0 && skills.every((s) => s.state === "pass" && (s.attempt || 1) === 1); }
function weeklyPassStats(reqs) { const now = new Date(); const day = now.getDay(); const monday = new Date(now); monday.setHours(0, 0, 0, 0); monday.setDate(now.getDate() - (day === 0 ? 6 : day - 1)); const weekReqs = reqs.filter((r) => new Date(r.createdAt) >= monday); return { total: weekReqs.length, onePass: weekReqs.filter(isOnePass).length }; }

export default function App() {
  const [reqs, setReqs] = useState([]), [works, setWorks] = useState([]), [projects, setProjects] = useState([]);
  const [activeProjectId, setActiveProjectId] = useState(null), [showAllProjects, setShowAllProjects] = useState(false);
  const [activeId, setActiveId] = useState(idFromUrl), [activeWorkId, setActiveWorkId] = useState(workIdFromUrl), [req, setReq] = useState(null);
  const [busy, setBusy] = useState(false), [err, setErr] = useState(null), [live, setLive] = useState(null), [retryNote, setRetryNote] = useState(null), [pending, setPending] = useState(null);
  const pendingFor = (id) => pending?.reqId === id ? pending.text : null; const send = (id, text, call) => { setPending({ reqId: id, text }); act(call); };
  const onEvent = useCallback((e) => setLive((cur) => { const s0 = cur || { text: "", tools: [], files: [] }; if (e.type === "text") return { ...s0, text: s0.text + e.text }; if (e.type === "tool") return { ...s0, tools: [...s0.tools, { n: e.n, a: e.a }] }; if (e.type === "file") return s0.files.includes(e.path) ? s0 : { ...s0, files: [...s0.files, e.path] }; if (e.type === "stage") return { ...s0, stages: [...(s0.stages || []), e.text] }; if (e.type === "step") return { text: "", tools: [], files: [], step: e.skill }; return s0; }), []);
  const refreshList = useCallback(async () => setReqs(await api.list()), []);
  const refreshWorks = useCallback(async () => setWorks(await api.works.list(showAllProjects ? null : activeProjectId)), [activeProjectId, showAllProjects]);
  useEffect(() => { refreshList(); }, [refreshList]); useEffect(() => { refreshWorks(); }, [refreshWorks]);
  useEffect(() => { api.projects.list().then((ps) => { setProjects(ps); if (ps.length && !activeProjectId) setActiveProjectId(ps[0].id); }); }, []);
  useEffect(() => { writeSelectionToUrl(activeId, activeWorkId); if (activeWorkId) { setReq(null); return; } if (!activeId) return setReq(null); api.get(activeId).then((r) => { if (!r || r.error) return setActiveId(null); setReq(r); if (r.projectId) setActiveProjectId(r.projectId); }); }, [activeId, activeWorkId]);
  useEffect(() => { if (!req?.running) return; return subscribeRun(req.id, (e) => { if (e.type === "run" || e.type === "closed") { api.get(req.id).then(setReq); setLive(null); if (e.type === "run" && e.state === "error") setErr(e.message); } else if (e.type === "ticket") setLive(null); else if (e.type === "step") { setLive({ text: "", tools: [], files: [], step: e.skill, attempt: e.attempt }); api.get(req.id).then(setReq); } else if (e.type === "retry") setRetryNote(`${e.ticket} ${e.skill} 未通过，正在重试一次：${e.reason || ""}`); else onEvent(e); }, () => api.get(req.id).then(setReq)); }, [req?.running, req?.id, onEvent]);
  async function act(fn) { setBusy(true); setErr(null); setLive(null); try { const next = await fn(); if (next?.error) setErr(next.error); else { setReq(next); refreshList(); } } catch (e) { setErr(e.message); } setBusy(false); setLive(null); setPending(null); }
  const visibleReqs = showAllProjects ? reqs : reqs.filter((r) => !activeProjectId || r.projectId === activeProjectId);
  return <div className="flex h-screen w-full bg-white text-sm text-neutral-900 antialiased">
    <Sidebar reqs={visibleReqs} works={works} allReqs={reqs} activeId={activeId} activeWorkId={activeWorkId} onPick={(id) => { setActiveWorkId(null); setActiveId(id); }} onPickWork={(id) => { setActiveId(null); setActiveWorkId(id); }} projects={projects} activeProjectId={activeProjectId} onProjectChange={setActiveProjectId} showAllProjects={showAllProjects} onToggleShowAll={() => setShowAllProjects((v) => !v)} onCreateProject={async (p) => { const created = await api.projects.create(p); if (!created?.error) { const ps = await api.projects.list(); setProjects(ps); setActiveProjectId(created.id); } return created; }} onCreate={async (title) => { if (!activeProjectId) return; const r = await api.create(title, activeProjectId); await refreshList(); setActiveWorkId(null); setActiveId(r.id); }} onCreateWork={async (title) => { if (!activeProjectId) return; const r = await api.works.create(title, activeProjectId); await refreshWorks(); setActiveId(null); setActiveWorkId(r.work?.id); }} />
    <main className="flex min-w-0 flex-1 flex-col">{activeWorkId ? <V5WorkView workId={activeWorkId} /> : !req ? <div className="flex flex-1 items-center justify-center text-neutral-500">选择一个 BUILD 工作，或打开旧版需求</div> : <><PhaseHeader req={req} busy={busy} onInvalidate={(back) => act(() => api.invalidate(req.id, back))} />{err && <div className="border-b border-red-200 bg-red-50 px-5 py-2 text-xs text-red-700">{err}</div>}{req.phase === "analysis" ? <Analysis req={req} busy={busy} live={live} pending={pendingFor(req.id)} onSend={(t) => send(req.id, t, () => api.message(req.id, t, onEvent))} onEdit={(s) => act(() => api.settled(req.id, s))} onHandoff={() => act(() => api.handoff(req.id, onEvent))} /> : <Implementation req={req} busy={busy} live={live} retryNote={retryNote} pending={pendingFor(req.id)} onStart={() => act(async () => { const r = await api.start(req.id); setRetryNote(null); return r; })} onStop={() => api.stop(req.id).then(() => api.get(req.id).then(setReq))} onRun={(ticket) => act(() => api.run(req.id, ticket, onEvent))} onSend={(t) => send(req.id, t, () => api.implMessage(req.id, t))} onInvalidate={(back) => act(() => api.invalidate(req.id, back))} onStepReset={(ticket, skillName) => act(() => api.stepReset(req.id, ticket, skillName))} onTicketReset={(ticket) => act(() => api.ticketReset(req.id, ticket))} onFailureReason={(reason) => act(() => api.failureReason(req.id, reason))} />}</>}</main>
  </div>;
}

function Sidebar({ reqs, works, allReqs, activeId, activeWorkId, onPick, onPickWork, projects, activeProjectId, onProjectChange, showAllProjects, onToggleShowAll, onCreateProject, onCreate, onCreateWork }) {
  const [adding, setAdding] = useState(false), [title, setTitle] = useState(""), [pickerOpen, setPickerOpen] = useState(false), [creatingProject, setCreatingProject] = useState(false);
  const activeProject = projects.find((p) => p.id === activeProjectId), stats = weeklyPassStats(showAllProjects ? allReqs : reqs);
  return <aside className="flex w-64 shrink-0 flex-col border-r border-neutral-200"><div className="relative flex h-12 shrink-0 items-center justify-between border-b border-neutral-200 px-4"><button onClick={() => setPickerOpen((v) => !v)} className="flex min-w-0 flex-1 items-center gap-1.5 rounded px-1 py-1 text-left hover:bg-neutral-50"><FolderGit2 className="h-3.5 w-3.5 shrink-0 text-neutral-400" /><span className="truncate font-medium">{activeProject?.name || "选择项目"}</span><ChevronsUpDown className="h-3 w-3 shrink-0 text-neutral-400" /></button><button onClick={() => setAdding(true)} className="shrink-0 rounded p-1 text-neutral-400 hover:bg-neutral-100 hover:text-neutral-900" title="新建工作"><Plus className="h-4 w-4" /></button>{pickerOpen && <div className="absolute left-0 top-12 z-10 w-72 rounded-md border border-neutral-200 bg-white p-1.5 shadow-lg">{projects.map((p) => <button key={p.id} onClick={() => { onProjectChange(p.id); setPickerOpen(false); }} className={`flex w-full items-center gap-2 rounded px-2 py-1.5 text-left text-xs ${p.id === activeProjectId ? "bg-neutral-100" : "hover:bg-neutral-50"}`}><span className="min-w-0 flex-1 truncate">{p.name}</span>{p.id === activeProjectId && <Check className="h-3 w-3 shrink-0 text-emerald-600" />}</button>)}<div className="my-1 border-t border-neutral-200" /><label className="flex items-center gap-2 px-2 py-1.5 text-xs text-neutral-600"><input type="checkbox" checked={showAllProjects} onChange={onToggleShowAll} />显示全部项目</label><button onClick={() => { setCreatingProject(true); setPickerOpen(false); }} className="flex w-full items-center gap-1.5 rounded px-2 py-1.5 text-left text-xs text-neutral-600 hover:bg-neutral-50"><Plus className="h-3 w-3" /> 新建项目</button></div>}</div>
    <div className="shrink-0 border-b border-neutral-200 px-4 py-2 text-xs text-neutral-500">v5 BUILD {works.length} · 旧需求本周 {stats.total}</div>
    {creatingProject && <NewProjectForm onCancel={() => setCreatingProject(false)} onCreate={async (p) => { const created = await onCreateProject(p); if (!created?.error) setCreatingProject(false); return created; }} />}
    {adding && <div className="shrink-0 border-b border-neutral-200 p-3"><input autoFocus value={title} onChange={(e) => setTitle(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && title.trim()) { onCreateWork(title.trim()); setTitle(""); setAdding(false); } if (e.key === "Escape") setAdding(false); }} placeholder="BUILD 工作标题，回车创建" className="w-full rounded-md border border-neutral-300 px-2.5 py-1.5 outline-none placeholder:text-neutral-400" /><button onClick={() => { if (title.trim()) { onCreate(title.trim()); setTitle(""); setAdding(false); } }} className="mt-2 text-xs text-neutral-400 hover:text-neutral-700">改为创建旧版需求</button></div>}
    <div className="flex-1 overflow-y-auto p-3"><div className="mb-2 px-1 text-[11px] font-medium uppercase tracking-wide text-neutral-400">BUILD</div><div className="space-y-0.5">{works.map((w) => <button key={w.id} onClick={() => onPickWork(w.id)} className={`flex w-full items-center gap-2 rounded-md px-2.5 py-2 text-left ${activeWorkId === w.id ? "bg-neutral-100" : "hover:bg-neutral-50"}`}><span className="flex-1 truncate">{w.title}</span><span className="text-[10px] text-neutral-400">v5</span></button>)}</div><div className="mb-2 mt-5 px-1 text-[11px] font-medium uppercase tracking-wide text-neutral-400">Legacy</div><div className="space-y-0.5">{reqs.map((r) => <button key={r.id} onClick={() => onPick(r.id)} className={`flex w-full items-center gap-2 rounded-md px-2.5 py-2 text-left ${activeId === r.id ? "bg-neutral-100" : "hover:bg-neutral-50"}`}><span className="flex-1 truncate">{r.title}</span><PhaseTag phase={r.phase} /></button>)}</div></div>
  </aside>;
}

function NewProjectForm({ onCreate, onCancel }) { const [name, setName] = useState(""), [repoPath, setRepoPath] = useState(""), [worktreesDir, setWorktreesDir] = useState(""), [baseBranch, setBaseBranch] = useState(""), [error, setError] = useState(null); async function submit() { setError(null); const created = await onCreate({ name: name.trim(), repoPath: repoPath.trim(), worktreesDir: worktreesDir.trim(), baseBranch: baseBranch.trim() }); if (created?.error) setError(created.error); } return <div className="shrink-0 space-y-1.5 border-b border-neutral-200 p-3"><input autoFocus value={name} onChange={(e) => setName(e.target.value)} placeholder="项目名称" className="w-full rounded-md border border-neutral-300 px-2.5 py-1.5 text-xs outline-none" /><input value={repoPath} onChange={(e) => setRepoPath(e.target.value)} placeholder="仓库路径 repoPath" className="w-full rounded-md border border-neutral-300 px-2.5 py-1.5 text-xs outline-none" /><input value={worktreesDir} onChange={(e) => setWorktreesDir(e.target.value)} placeholder="worktree 目录 worktreesDir" className="w-full rounded-md border border-neutral-300 px-2.5 py-1.5 text-xs outline-none" /><input value={baseBranch} onChange={(e) => setBaseBranch(e.target.value)} placeholder="基线分支（可留空）" className="w-full rounded-md border border-neutral-300 px-2.5 py-1.5 text-xs outline-none" />{error && <p className="text-xs text-red-600">{error}</p>}<div className="flex gap-1.5"><button onClick={submit} disabled={!name.trim() || !repoPath.trim() || !worktreesDir.trim()} className="flex-1 rounded-md bg-neutral-900 px-2.5 py-1.5 text-xs font-medium text-white disabled:opacity-30">创建</button><button onClick={onCancel} className="rounded-md border border-neutral-200 px-2.5 py-1.5 text-xs">取消</button></div></div>; }
function PhaseTag({ phase }) { const map = { analysis: ["分析", "bg-neutral-100 text-neutral-600"], impl: ["实现", "bg-blue-50 text-blue-700"], done: ["完成", "bg-neutral-50 text-neutral-400"] }; const [label, cls] = map[phase] || map.analysis; return <span className={`rounded px-1.5 py-0.5 text-xs ${cls}`}>{label}</span>; }
function PhaseHeader({ req, busy, onInvalidate }) { return <header className="flex h-12 shrink-0 items-center gap-3 border-b border-neutral-200 px-5"><span className="font-medium">{req.title}</span><span className="font-mono text-xs text-neutral-400">{req.id}</span><div className="ml-4 flex items-center gap-2 text-xs"><span className={req.phase === "analysis" ? "font-medium" : "text-neutral-400"}>需求分析</span><ArrowRight className="h-3 w-3 text-neutral-300" /><span className={req.phase !== "analysis" ? "font-medium" : "text-neutral-400"}>实现</span></div>{busy && <Loader2 className="h-3.5 w-3.5 animate-spin text-neutral-400" />}{req.phase !== "analysis" && <button onClick={() => onInvalidate(false)} className="ml-auto flex items-center gap-1.5 rounded-md border border-neutral-200 px-2.5 py-1 text-xs text-neutral-600"><RotateCcw className="h-3 w-3" />作废重跑</button>}</header>; }

/* Legacy v4 screens retained below. */
function Analysis({ req, busy, live, pending, onSend, onEdit, onHandoff }) {
  const [input, setInput] = useState(""); const [handingOff, setHandingOff] = useState(false); useEffect(() => { if (!busy) setHandingOff(false); }, [busy]); const ref = useRef(null); useEffect(() => { if (ref.current) ref.current.scrollTop = ref.current.scrollHeight; }, [req.dialog, pending, busy, live?.text]); const ready = req.settled.open.length === 0 && req.settled.fixed.length > 0;
  return <div className="flex min-h-0 flex-1"><div className="flex min-w-0 flex-1 flex-col"><div ref={ref} className="flex-1 overflow-y-auto"><div className="mx-auto max-w-2xl px-6 py-6">{req.dialog.length === 0 && !pending && <p className="text-neutral-500">描述你想做什么。代理会先澄清需求，不会立即改代码。</p>}{req.dialog.map((m, i) => <Message key={i} role={m.role} text={m.text} />)}{pending && <Message role="user" text={pending} />}{busy && <LiveMessage live={live} />}</div></div><Composer value={input} onChange={setInput} disabled={busy} placeholder="补充需求或回答问题…" onSend={() => { if (!input.trim()) return; onSend(input.trim()); setInput(""); }} /></div><aside className="w-80 shrink-0 overflow-y-auto border-l border-neutral-200 p-4"><SettledPanel settled={req.settled} onEdit={onEdit} disabled={busy} />{ready && <button onClick={() => { setHandingOff(true); onHandoff(); }} disabled={busy} className="mt-4 flex w-full items-center justify-center gap-2 rounded-md bg-neutral-900 px-3 py-2 text-xs font-medium text-white disabled:opacity-50">{handingOff ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <ArrowRight className="h-3.5 w-3.5" />}{handingOff ? "正在生成规格与工单…" : "生成规格并移交实现"}</button>}</aside></div>;
}
function Message({ role, text }) { return <div className={`mb-5 ${role === "user" ? "ml-12" : "mr-12"}`}><div className="mb-1 text-xs text-neutral-400">{role === "user" ? "你" : "代理"}</div><div className={`whitespace-pre-wrap leading-6 ${role === "user" ? "rounded-lg bg-neutral-100 px-3 py-2" : ""}`}>{text}</div></div>; }
function LiveMessage({ live }) { return <div className="mr-12 mb-5"><div className="mb-1 flex items-center gap-2 text-xs text-neutral-400"><Loader2 className="h-3 w-3 animate-spin" />代理执行中</div>{live?.text && <div className="whitespace-pre-wrap leading-6">{stripProtocol(live.text)}</div>}</div>; }
function Composer({ value, onChange, onSend, disabled, placeholder }) { return <div className="border-t border-neutral-200 p-4"><div className="mx-auto flex max-w-2xl gap-2"><input value={value} onChange={(e) => onChange(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); onSend(); } }} disabled={disabled} placeholder={placeholder} className="min-w-0 flex-1 rounded-md border border-neutral-300 px-3 py-2 outline-none disabled:bg-neutral-50" /><button onClick={onSend} disabled={disabled || !value.trim()} className="rounded-md bg-neutral-900 px-3 text-white disabled:opacity-30"><CornerDownLeft className="h-4 w-4" /></button></div></div>; }
function SettledPanel({ settled, onEdit, disabled }) { return <div><div className="mb-2 text-xs font-medium text-neutral-500">已确定</div>{settled.fixed.length === 0 && <p className="text-xs text-neutral-400">暂无</p>}{settled.fixed.map((x) => <div key={x.k} className="mb-2 rounded border border-neutral-200 p-2"><div className="text-xs text-neutral-400">{x.k}</div><div>{x.v}</div></div>)}{settled.open.length > 0 && <><div className="mb-2 mt-4 text-xs font-medium text-amber-600">待确认</div>{settled.open.map((x) => <div key={x.k} className="mb-2 rounded border border-amber-100 bg-amber-50 p-2"><div className="text-xs text-amber-600">{x.k}</div><div>{x.v}</div></div>)}</>}<button disabled={disabled} onClick={() => onEdit(settled)} className="mt-2 flex items-center gap-1 text-xs text-neutral-400"><Pencil className="h-3 w-3" />编辑</button></div>; }
function Implementation({ req, busy, live, retryNote, pending, onStart, onStop, onRun, onSend, onInvalidate, onStepReset, onTicketReset, onFailureReason }) { const [input, setInput] = useState(""); return <div className="flex min-h-0 flex-1"><div className="flex-1 overflow-y-auto p-5"><div className="mx-auto max-w-4xl">{retryNote && <div className="mb-3 rounded bg-amber-50 p-2 text-xs text-amber-700">{retryNote}</div>}<div className="space-y-3">{(req.tickets || []).map((t) => <div key={t.ticket} className="rounded-lg border border-neutral-200 p-3"><div className="flex items-center gap-2"><span className="font-mono text-xs text-neutral-400">{t.ticket}</span><span className="font-medium">{t.title}</span><button onClick={() => onRun(t.ticket)} disabled={busy || req.running} className="ml-auto rounded border px-2 py-1 text-xs disabled:opacity-30"><Play className="mr-1 inline h-3 w-3" />运行</button></div><div className="mt-2 flex gap-2">{t.skills.map((s) => <span key={s.name} className="rounded bg-neutral-50 px-2 py-1 text-xs">{s.name}: {s.state}{fmtMs(s.ms) ? ` · ${fmtMs(s.ms)}` : ""}</span>)}</div></div>)}</div>{busy && <LiveMessage live={live} />}</div></div><div className="w-80 border-l border-neutral-200 p-4"><button onClick={req.running ? onStop : onStart} className="mb-4 w-full rounded bg-neutral-900 px-3 py-2 text-xs text-white">{req.running ? "停止自动执行" : "自动执行"}</button><Composer value={input} onChange={setInput} disabled={busy} placeholder="给实现代理补充指令…" onSend={() => { if (input.trim()) { onSend(input.trim()); setInput(""); } }} /></div></div>; }
