import React, { useCallback, useEffect, useState } from "react";
const STATUS_TEXT = { draft: "准备中", active: "进行中", waiting_user: "等待确认", completed: "已完成", failed: "失败", idle: "待开始", running: "执行中", recovering: "正在处理问题", ready: "可开始", blocked: "等待依赖" };
async function post(url, body) { return fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }).then((r) => r.json()); }
async function streamPost(url, body, onEvent) { const res = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const reader = res.body.getReader(); const dec = new TextDecoder(); let buf = "", final = null; for (;;) { const { done, value } = await reader.read(); if (done) break; buf += dec.decode(value, { stream: true }); const lines = buf.split("\n"); buf = lines.pop() || ""; for (const line of lines) { if (!line.trim()) continue; const e = JSON.parse(line); if (e.type === "done") final = e.req; else if (e.type === "error") throw new Error(e.message); else onEvent?.(e); } } return final; }
function ActivityRow({ activity, engineering }) { return <div className="border-b border-slate-100 py-3 last:border-0"><div className="flex items-center justify-between gap-3"><div className="font-medium text-slate-800">{activity.parentActivityId ? "↳ " : ""}{activity.label}</div><span className="text-xs text-slate-500">{STATUS_TEXT[activity.status] || activity.status}</span></div>{engineering && <div className="mt-1 font-mono text-xs text-slate-400">{activity.technical?.skill ? `/${activity.technical.skill}` : activity.type}{activity.sessionId ? ` · ${activity.sessionId}` : ""}{activity.recoveryFor ? ` · recovery ${activity.recoveryFor}` : ""}</div>}</div>; }
function TicketRow({ ticket, engineering }) { return <div className="rounded-lg border border-slate-200 p-3"><div className="flex items-start justify-between gap-3"><div><span className="mr-2 text-xs text-slate-400">#{ticket.number}</span>{ticket.title}</div><span className="text-xs text-slate-500">{STATUS_TEXT[ticket.status] || ticket.status}</span></div>{engineering && <div className="mt-2 text-xs text-slate-500">{ticket.blockedBy?.length ? `依赖：${ticket.blockedBy.join(", ")}` : "无未完成依赖"}{ticket.path ? <div className="mt-1 truncate font-mono text-slate-400">{ticket.path}</div> : null}</div>}</div>; }

export default function V5WorkView({ workId, apiBase = "" }) {
  const [data, setData] = useState(null), [tickets, setTickets] = useState(null), [engineering, setEngineering] = useState(false), [error, setError] = useState(""), [busy, setBusy] = useState(false), [live, setLive] = useState(""), [stage, setStage] = useState("");
  const refresh = useCallback(async () => { if (!workId) return; const [work, frontier] = await Promise.all([fetch(`${apiBase}/api/v5/works/${workId}`).then((r) => r.json()), fetch(`${apiBase}/api/v5/works/${workId}/tickets`).then((r) => r.json())]); setData(work); setTickets(frontier); }, [workId, apiBase]);
  useEffect(() => { refresh().catch((e) => setError(e.message)); }, [refresh]);
  async function advance() { setBusy(true); setError(""); setLive(""); setStage(""); try { await streamPost(`${apiBase}/api/v5/build/advance`, { workId }, (e) => { if (e.type === "text") setLive((s) => s + e.text); if (e.type === "orchestrator") setStage(e.state); }); await refresh(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function decide(activity, decision) { setBusy(true); setError(""); try { const r = await post(`${apiBase}/api/v5/activities/${activity.id}/gate`, { workId, decision }); if (r.error) throw new Error(r.error); await refresh(); if (decision === "approve") await advance(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  if (!workId) return null; if (!data?.work) return <div className="p-4 text-sm text-slate-400">加载工作进度…</div>;
  const gate = data.activities?.find((a) => a.status === "waiting_user" && a.gate);
  const recovering = data.activities?.some((a) => a.status === "recovering") || data.interruptions?.some((x) => x.status === "recovering");
  const latestInterruption = data.interruptions?.slice().reverse().find((x) => !["resolved"].includes(x.status));
  const canStart = !busy && !gate && !recovering && !["completed"].includes(data.work.status);
  return <section className="mx-auto max-w-4xl space-y-4 p-4">
    <header className="flex items-start justify-between gap-4"><div><div className="text-xs uppercase tracking-wide text-slate-400">BUILD · {STATUS_TEXT[data.work.status] || data.work.status}</div><h1 className="mt-1 text-xl font-semibold text-slate-900">{data.work.title}</h1><p className="mt-1 text-xs text-slate-400">自动推进，只有需要你决策时才会停下。</p></div><div className="flex gap-2">{canStart && <button onClick={advance} className="rounded-md bg-slate-900 px-3 py-1.5 text-xs text-white">{data.work.status === "draft" ? "开始 BUILD" : "继续执行"}</button>}<button className="rounded-md border border-slate-200 px-3 py-1.5 text-xs text-slate-600" onClick={() => setEngineering((v) => !v)}>{engineering ? "简洁视图" : "工程详情"}</button></div></header>
    {recovering && <div className="rounded-xl border border-blue-100 bg-blue-50 p-4"><div className="text-xs font-medium text-blue-700">AI 正在自动处理一个执行问题</div><div className="mt-1 text-sm text-slate-700">无需操作，处理完成后 BUILD 会继续原任务。</div>{engineering && latestInterruption && <div className="mt-2 font-mono text-xs text-slate-500">{latestInterruption.type} · {latestInterruption.recovery?.strategy} · attempt {latestInterruption.recovery?.attempt}/{latestInterruption.recovery?.maxAttempts}</div>}</div>}
    {gate && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="text-xs font-medium text-amber-700">需要你的确认</div><div className="mt-1 font-medium text-slate-900">{gate.gate.prompt || gate.label}</div>{engineering && latestInterruption && <div className="mt-2 font-mono text-xs text-amber-700">{latestInterruption.type} · {latestInterruption.signature}</div>}<div className="mt-3 flex gap-2"><button disabled={busy} onClick={() => decide(gate, "approve")} className="rounded bg-slate-900 px-3 py-1.5 text-xs text-white disabled:opacity-40">确认并继续</button><button disabled={busy} onClick={() => decide(gate, "revise")} className="rounded border border-amber-300 bg-white px-3 py-1.5 text-xs text-amber-800 disabled:opacity-40">需要调整</button></div></div>}
    {error && <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    {busy && <div className="rounded border border-blue-100 bg-blue-50 p-3 text-xs text-blue-700">BUILD 正在自动执行{stage ? ` · ${stage}` : ""}…</div>}
    {live && engineering && <pre className="max-h-48 overflow-auto whitespace-pre-wrap rounded bg-slate-950 p-3 text-xs text-slate-200">{live}</pre>}
    <div className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="mb-1 text-sm font-semibold text-slate-700">当前流程</h2>{data.activities?.map((activity) => <ActivityRow key={activity.id} activity={activity} engineering={engineering} />)}</div>
    <div className="rounded-xl border border-slate-200 bg-white p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold text-slate-700">开发任务</h2>{tickets?.counts && <span className="text-xs text-slate-400">{tickets.counts.completed}/{tickets.counts.total} 完成</span>}</div>{!tickets?.tickets?.length ? <div className="text-sm text-slate-400">计划确认后，BUILD 会自动执行可开始的开发任务。</div> : <div className="space-y-2">{tickets.tickets.map((ticket) => <TicketRow key={ticket.id} ticket={ticket} engineering={engineering} />)}</div>}{engineering && tickets?.issuesDir && <div className="mt-3 truncate font-mono text-xs text-slate-400">source: {tickets.issuesDir}</div>}</div>
  </section>;
}
